name: opendungeons
version: 0.8.0
confinement: strict
summary: OpenDungeons
base: core18
description: Open source game inspired by Dungeon Keeper - Dark, damp and dangerous.

apps:
    opendungeons:
        command: desktop-launch $SNAP/usr/games/opendungeons
        environment:
            CEGUI_MODULE_DIR: $SNAP/usr/lib/cegui-0.9999
        plugs: [opengl, x11, pulseaudio, network, network-bind]
        desktop: usr/share/applications/opendungeons.desktop
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_CONFIG_THREAD_PROVIDER=std
            - -DOGRE_CONFIG_THREADS=3
            - -DOGRE_STATIC=FALSE
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_RESOURCEMANAGER_STRICT=0
            # stuff we dont need
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=FALSE
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_FREEIMAGE=FALSE
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_PAGING=FALSE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DOGRE_BUILD_COMPONENT_HLMS=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
        source: https://github.com/OGRECave/ogre.git
        source-tag: v1.12.5
        source-depth: 1
        build-packages:
            - libxaw7-dev
            - libzzip-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libxt-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - g++
        stage-packages:
            - libfreetype6
            - libzzip-0-13
            - libxaw7
            - libxt6
    cegui:
        plugin: cmake
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_FLAGS=-std=c++11
            - -DCEGUI_BUILD_RENDERER_OPENGL=FALSE
            - -DCEGUI_BUILD_RENDERER_OPENGL3=FALSE
            - -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=FALSE # we use ogre
            - -DCEGUI_SAMPLES_ENABLED=FALSE
        source: https://github.com/cegui/cegui.git
        source-depth: 1
        source-tag: v0
        build-packages:
            - librapidxml-dev
        override-pull: |
            snapcraftctl pull
            sed -i -e 's|target_compile_features|\#target_compile_features|g' cegui/src/RendererModules/Ogre/CMakeLists.txt
        after: [ogre]
    opendungeons:
        plugin: cmake
        source: https://github.com/paroj/OpenDungeons.git
        source-tag: snapcraft
        source-depth: 1
        override-pull: |
            snapcraftctl pull
            sed -i -e 's|if(CMAKE_INSTALL_PREFIX|if(""|g' CMakeLists.txt
        configflags:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_FLAGS=-std=c++11
        override-build: |
            snapcraftctl build
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/etc/opendungeons/plugins.cfg # drop stage prefix
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/usr/share/games/opendungeons/resources.cfg # drop stage prefix
        build-packages:
            - libsfml-dev
            - libois-dev
            - libboost-thread-dev
            - libboost-locale-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
        stage-packages:
            - libsfml-window2.4
            - libsfml-audio2.4
            - libsfml-system2.4
            - libsfml-network2.4
            - libboost-thread1.65.1
            - libboost-program-options1.65.1
            - libboost-filesystem1.65.1
            - libboost-system1.65.1
            - libboost-locale1.65.1
            - libois-1.3.0v5
            - libpulse0
        after: [ogre, cegui, desktop-glib-only]
